export const SUB_COMPANIES_INDEX_REQUEST = 'SUB_COMPANIES_INDEX_REQUEST';
export const SUB_COMPANIES_INDEX_SUCCESS = 'SUB_COMPANIES_INDEX_SUCCESS';
export const SUB_COMPANIES_INDEX_FAILURE = 'SUB_COMPANIES_INDEX_FAILURE';
