export const COMPANY_STATIONS_INDEX_REQUEST = 'COMPANY_STATIONS_INDEX_REQUEST';
export const COMPANY_STATIONS_INDEX_SUCCESS = 'COMPANY_STATIONS_INDEX_SUCCESS';
export const COMPANY_STATIONS_INDEX_FAILURE = 'COMPANY_STATIONS_INDEX_FAILURE';
